apiVersion: v1
kind: PersistentVolume
metadata:
  name: istio-sidecar-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany   # Allow multiple pods to write
  hostPath:
    path: "/var/log/istio-sidecar"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-sidecar-logs-pvc
spec:
  accessModes:
    - ReadWriteMany   # Multiple pods can write logs
  resources:
    requests:
      storage: 10Gi
