apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: tarang412/service-b:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: DB_HOST
            value: "mysql.default.svc.cluster.local"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
