apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: tarang412/service-c:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: SERVICE_B_URL
          valueFrom:
            secretKeyRef:
              name: service-config-secret
              key: SERVICE_B_URL
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: AUTH0_DOMAIN
