apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-c
  namespace: default
