apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-a
  namespace: default
spec:
  hosts:
  - "*"  # Accept requests from anywhere
  gateways:
  - istio-system/service-a-gateway  # External traffic via Istio Ingress
  http:
  - match:
    - uri:
        prefix: /products
    route:
    - destination:
        host: service-a.default.svc.cluster.local
        port:
          number: 8082
