apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-c
  namespace: default
spec:
  hosts:
  - service-c.default.svc.cluster.local  # Internal service
  http:
  - match:
    - uri:
        prefix: /products
    route:
    - destination:
        host: service-c.default.svc.cluster.local
        port:
          number: 8083
