apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-c-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/service-c-logs"  # Service C logs stored on worker node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-c-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: istio-c-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/istio-c-logs"  # Istio proxy logs stored separately

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-c-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
