apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-b-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/service-b-logs"  # ✅ Service B logs stored on worker node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-b-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: istio-b-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/istio-b-logs"  # ✅ Istio Proxy logs stored separately

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-b-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
